#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  8 12:27:54 2020

@author: bryce
"""

# wheel = (1,2,3,4,5,6,7,8,9,10)

# wheel = (1,2,3,4,5,6,7,8,9,10)
from random import randint
wheel = {0 : 'You lose 50% of your earnings, your total is: ', 1 :'game over', 2 :'game over', 3 :'game over', 4 :4, 5 :5, 6: 6, 7 :14, 8 :16, 9 :18, 10 : 20}
# Dictonary containing the outcome of the spin

spin = randint(0, 10)
# random spin to allow the function to work 
print(f'This was the wheel spin {spin}')



def wheel_spins(spin):
    num = 0                             # allows the the while function to keep iterating on the 50% loss
    earnings = 0
    win_list = []
    while spin == 0 or spin > 3:
        if spin == 0: 
            print(wheel[0])
            earnings = earnings/2
            num += 1
            spin = randint(0, 10)       # calls new spin if 0 is spun
            print(f'${earnings:.2f}')
            print(' ')
            print(f'This was the wheel spin {spin}')
        elif spin > 3:                  # this is records all of the winnings
            earnings += wheel[spin]
            spin = randint(0, 10)
            print(f'This is what you have earned so far: ${earnings:.2f}')
            print(' ')
            print(f'This is what you spun {spin}') 
                        
    
    else:                               # this ends the function if numbers 1,2,3 are spun
        print(' ')
        print('You are done now')
        print(f'Your total winnings is ${earnings:.2f}')
        win_list.append(earnings)

wheel_spins(spin)




x = 0   
   
def simulations(x):
    x = int(input('How many simulations would you like to run '))
    for i in range(0, x):
        wheel_spins(spin)
        print(' ')
        
simulations(x)




